### PR TITLE
Fixed incorrect width in publish page

### PR DESCRIPTION
**Pull request by soorajbhskrn**
Fixes https://github.com/bigbinary/neeto-site-web/issues/327

Updated the following:

- [x] Matched published site width draft preview width

@AbhayVAshokan _a
Please check.

SS:
Screenshot 2022-12-29 at 6 49 59 PM

### CODE REVIEW

**Review by AbhayVAshokan — APPROVED** [review]
LGTM

@soorajbhskrn _a one more small change to make sure that both preview and EUI match. Replace `styles/globals.css` with:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  font-family: system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
    Oxygen, Ubuntu, Fira Sans, Droid Sans, Helvetica Neue, sans-serif !important;
}
```

**Comment by soorajbhskrn** [comment]
Please check
@AbhayVAshokan _a

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@soorajbhskrn _a please replace the entire file. We don't need to import `Inter` anymore. We shall bring in the font family logic later.

**Comment by soorajbhskrn** [comment]
Done
@AbhayVAshokan _a

**Review by AbhayVAshokan — APPROVED** [review]

**Pull request merged**
