### PR TITLE
Added ability to show custom title

### PR DESCRIPTION
**Pull request by soorajbhskrn**
Fixes [#409](https://github.com/bigbinary/neeto-site-web/issues/409)

- Added  header for showing the site title

@AbhayVAshokan _a
Please check.

### CODE REVIEW

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
1. Use `name` instead of `site_title`.
2. We will be receiving `meta_description` as well from the API.
3. Please refer to this n[eetoKB file](https://github.com/bigbinary/neeto-kb-web/blob/main/app/views/kb/_head.html.erb) and add all the meta tags that will be useful for our site. You may do some exploration on your own and add anything else which would be useful.
4. Please remove everything inside the `Head` tag in `_document.js` file.

**Comment by soorajbhskrn** [comment]
> 3. Please refer to this n[eetoKB file](https://github.com/bigbinary/neeto-kb-web/blob/main/app/views/kb/_head.html.erb) and add all the meta tags that will be useful for our site. You may do some exploration on your own and add anything else which would be useful.

I think it would be nice if we give the end-user the option to add keywords relevant to their website which helps to improve SEO of their website

**Comment by soorajbhskrn** [comment]
@AbhayVAshokan _a
I have made some changes. 
Please check

**Review by AbhayVAshokan — CHANGES_REQUESTED** [review]
@soorajbhskrn _a it should be possible to add the twitter and opengraph meta tags as well.

`name` can be added to twitter:title, twitter:site, og:title, and og:site_name. Similarly meta_description can be added to description. We can add images after adding favicon.

https://github.com/bigbinary/neeto-kb-web/blob/main/app/views/kb/_head.html.erb#L17-L30

**Comment by soorajbhskrn** [comment]
Made some changes 
@AbhayVAshokan _a
Please check.

**Review by AbhayVAshokan — APPROVED** [review]

**Pull request merged**
